"""Add role column for Conversation table

Revision ID: 0b8bb932ebe3
Revises: 9e18329b7177
Create Date: 2024-09-22 01:26:10.812158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8bb932ebe3'
down_revision = '9e18329b7177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convo', schema=None) as batch_op:
        # Step 1: Add the role column as nullable first
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # Step 2: Update existing rows to set a default value for the new column
    op.execute("UPDATE convo SET role = 'user' WHERE role IS NULL")

    # Step 3: Alter the column to make it non-nullable
    with op.batch_alter_table('convo', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convo', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
