"""Add lastCommitHash column for PR table

Revision ID: 1f705bc05b73
Revises: 76152f22da23
Create Date: 2024-09-25 12:31:43.345300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f705bc05b73'
down_revision = '76152f22da23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastCommitHash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.drop_column('lastCommitHash')

    # ### end Alembic commands ###
