"""Adding created_date & last_modified

Revision ID: 22f17bf192a5
Revises: 
Create Date: 2024-09-23 00:58:26.454832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f17bf192a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PR',
    sa.Column('pr_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sourceBranchName', sa.String(), nullable=False),
    sa.Column('targetBranchName', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('initialFeedback', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pr_id'),
    sa.UniqueConstraint('pr_id')
    )
    op.create_table('convo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['PR.pr_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convo')
    op.drop_table('PR')
    # ### end Alembic commands ###
