"""Update  PR table

Revision ID: 277f376f7684
Revises: b6fc16263c21
Create Date: 2024-09-17 20:40:14.875457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277f376f7684'
down_revision = 'b6fc16263c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
