"""Adding pr_url

Revision ID: 3431262008f4
Revises: 0b8bb932ebe3
Create Date: 2024-09-22 14:53:12.915497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3431262008f4'
down_revision = '0b8bb932ebe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pr_url', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.drop_column('pr_url')

    # ### end Alembic commands ###
