"""Add rawDiff column for PR table

Revision ID: 76152f22da23
Revises: 0caffb967cf3
Create Date: 2024-09-25 00:54:23.888136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76152f22da23'
down_revision = '0caffb967cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rawDiff', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.drop_column('rawDiff')

    # ### end Alembic commands ###
