"""Remove pr_url

Revision ID: 994dbfa7790e
Revises: 3431262008f4
Create Date: 2024-09-22 16:59:15.926380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994dbfa7790e'
down_revision = '3431262008f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.drop_column('pr_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pr_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
