"""Add initialFeedback column for PR table

Revision ID: 9e18329b7177
Revises: ced89b8d59c1
Create Date: 2024-09-22 00:47:28.354976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e18329b7177'
down_revision = 'ced89b8d59c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initialFeedback', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['pr_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PR', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('initialFeedback')

    # ### end Alembic commands ###
