"""Initial migration - create PR table

Revision ID: a40227ba8cc9
Revises: 
Create Date: 2024-09-14 00:06:49.713608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40227ba8cc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PR',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.String(length=200), nullable=False),
    sa.Column('sourceBranchName', sa.String(length=200), nullable=False),
    sa.Column('targetBranchName', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )
    op.drop_table('PR')
    # ### end Alembic commands ###
