"""Initial migration after reset

Revision ID: ced89b8d59c1
Revises: 
Create Date: 2024-09-21 00:02:31.016097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced89b8d59c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PR',
    sa.Column('pr_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sourceBranchName', sa.String(), nullable=False),
    sa.Column('targetBranchName', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pr_id'),
    sa.UniqueConstraint('pr_id')
    )
    op.create_table('convo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['PR.pr_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convo')
    op.drop_table('PR')
    # ### end Alembic commands ###
